package com.doxacore.util;


import com.doxacore.modelo.Ciudad;
import com.doxacore.modelo.Departamento;
import com.doxacore.modelo.Pais;

public class CargarPaisDepartamentoCiudad {
	
	public static Pais cargarPais(Register reg) {
		
		Pais pais = new Pais();
		pais.setPais("Paraguay");
		pais.setGentilicio("Paraguayo/a");
		pais = reg.saveObject(pais, "System");
		
		return pais;
		
	}

	public static void cargarDC(Register reg, Pais pais) {
		
	
		
		String datos = "ASUNCION,ASUNCION;" + 
				"CONCEPCION,CONCEPCION;" + 
				"CONCEPCION,BELEN;" + 
				"CONCEPCION,HORQUETA;" + 
				"CONCEPCION,LORETO;" + 
				"CONCEPCION,SAN CARLOS DEL APA;" + 
				"CONCEPCION,SAN LAZARO;" + 
				"CONCEPCION,YBY YAU;" + 
				"CONCEPCION,AZOTE'Y;" + 
				"CONCEPCION,SARGENTO JOSE FELIX LOPEZ;" + 
				"CONCEPCION,SAN ALFREDO;" + 
				"CONCEPCION,PASO BARRETO;" + 
				"SAN PEDRO,SAN PEDRO DEL YCUAMANDYYU;" + 
				"SAN PEDRO,ANTEQUERA;" + 
				"SAN PEDRO,CHORE;" + 
				"SAN PEDRO,GENERAL ELIZARDO AQUINO;" + 
				"SAN PEDRO,ITACURUBI DEL ROSARIO;" + 
				"SAN PEDRO,LIMA;" + 
				"SAN PEDRO,NUEVA GERMANIA;" + 
				"SAN PEDRO,SAN ESTANISLAO;" + 
				"SAN PEDRO,SAN PABLO;" + 
				"SAN PEDRO,TACUATI;" + 
				"SAN PEDRO,UNION;" + 
				"SAN PEDRO,25 DE DICIEMBRE;" + 
				"SAN PEDRO,VILLA DEL ROSARIO;" + 
				"SAN PEDRO,GENERAL FRANCISCO ISIDORO RESQUIN;" + 
				"SAN PEDRO,YATAITY DEL NORTE;" + 
				"SAN PEDRO,GUAJAYVI;" + 
				"SAN PEDRO,CAPIIBARY;" + 
				"SAN PEDRO,SANTA ROSA DEL AGUARAY;" + 
				"SAN PEDRO,YRYBUCUA;" + 
				"SAN PEDRO,LIBERACION;" + 
				"CORDILLERA,CAACUPE;" + 
				"CORDILLERA,ALTOS;" + 
				"CORDILLERA,ARROYOS Y ESTEROS;" + 
				"CORDILLERA,ATYRA;" + 
				"CORDILLERA,CARAGUATAY;" + 
				"CORDILLERA,EMBOSCADA;" + 
				"CORDILLERA,EUSEBIO AYALA;" + 
				"CORDILLERA,ISLA PUCU;" + 
				"CORDILLERA,ITACURUBI DE LA CORDILLERA;" + 
				"CORDILLERA,JUAN DE MENA;" + 
				"CORDILLERA,LOMA GRANDE;" + 
				"CORDILLERA,MBOCAYATY DEL YHAGUY;" + 
				"CORDILLERA,NUEVA COLOMBIA;" + 
				"CORDILLERA,PIRIBEBUY;" + 
				"CORDILLERA,PRIMERO DE MARZO;" + 
				"CORDILLERA,SAN BERNARDINO;" + 
				"CORDILLERA,SANTA ELENA;" + 
				"CORDILLERA,TOBATI;" + 
				"CORDILLERA,VALENZUELA;" + 
				"CORDILLERA,SAN JOSE OBRERO;" + 
				"GUAIRA,VILLARRICA;" + 
				"GUAIRA,BORJA;" + 
				"GUAIRA,CAPITAN MAURICIO JOSE TROCHE;" + 
				"GUAIRA,CORONEL MARTINEZ;" + 
				"GUAIRA,FELIX PEREZ CARDOZO;" + 
				"GUAIRA,GRAL. EUGENIO A. GARAY;" + 
				"GUAIRA,INDEPENDENCIA;" + 
				"GUAIRA,ITAPE;" + 
				"GUAIRA,ITURBE;" + 
				"GUAIRA,JOSE FASSARDI;" + 
				"GUAIRA,MBOCAYATY;" + 
				"GUAIRA,NATALICIO TALAVERA;" + 
				"GUAIRA,NUMI;" + 
				"GUAIRA,SAN SALVADOR;" + 
				"GUAIRA,YATAITY;" + 
				"GUAIRA,DOCTOR BOTTRELL;" + 
				"GUAIRA,PASO YOBAI;" + 
				"GUAIRA,TEBICUARY;" + 
				"CAAGUAZU,CORONEL OVIEDO;" + 
				"CAAGUAZU,CAAGUAZU;" + 
				"CAAGUAZU,CARAYAO;" + 
				"CAAGUAZU,DR. CECILIO BAEZ;" + 
				"CAAGUAZU,SANTA ROSA DEL MBUTUY;" + 
				"CAAGUAZU,DR. JUAN MANUEL FRUTOS;" + 
				"CAAGUAZU,REPATRIACION;" + 
				"CAAGUAZU,NUEVA LONDRES;" + 
				"CAAGUAZU,SAN JOAQUIN;" + 
				"CAAGUAZU,SAN JOSE DE LOS ARROYOS;" + 
				"CAAGUAZU,YHU;" + 
				"CAAGUAZU,DR. J. EULOGIO ESTIGARRIBIA;" + 
				"CAAGUAZU,R.I. 3 CORRALES;" + 
				"CAAGUAZU,RAUL ARSENIO OVIEDO;" + 
				"CAAGUAZU,JOSE DOMINGO OCAMPOS;" + 
				"CAAGUAZU,MARISCAL FRANCISCO SOLANO LOPEZ;" + 
				"CAAGUAZU,LA PASTORA;" + 
				"CAAGUAZU,3 DE FEBRERO;" + 
				"CAAGUAZU,SIMON BOLIVAR;" + 
				"CAAGUAZU,VAQUERIA;" + 
				"CAAGUAZU,TEMBIAPORA;" + 
				"CAAGUAZU,NUEVA TOLEDO;" + 
				"CAAZAPA,CAAZAPA;" + 
				"CAAZAPA,ABAI;" + 
				"CAAZAPA,BUENA VISTA;" + 
				"CAAZAPA,DR. MOISES S. BERTONI;" + 
				"CAAZAPA,GRAL. HIGINIO MORINIGO;" + 
				"CAAZAPA,MACIEL;" + 
				"CAAZAPA,SAN JUAN NEPOMUCENO;" + 
				"CAAZAPA,TAVAI;" + 
				"CAAZAPA,YEGROS;" + 
				"CAAZAPA,YUTY;" + 
				"CAAZAPA,3 DE MAYO;" + 
				"ITAPUA,ENCARNACION;" + 
				"ITAPUA,BELLA VISTA;" + 
				"ITAPUA,CAMBYRETA;" + 
				"ITAPUA,CAPITAN MEZA;" + 
				"ITAPUA,CAPITAN MIRANDA;" + 
				"ITAPUA,NUEVA ALBORADA;" + 
				"ITAPUA,CARMEN DEL PARANA;" + 
				"ITAPUA,CORONEL BOGADO;" + 
				"ITAPUA,CARLOS ANTONIO LOPEZ;" + 
				"ITAPUA,NATALIO;" + 
				"ITAPUA,FRAM;" + 
				"ITAPUA,GENERAL ARTIGAS;" + 
				"ITAPUA,GENERAL DELGADO;" + 
				"ITAPUA,HOHENAU;" + 
				"ITAPUA,JESUS;" + 
				"ITAPUA,JOSE LEANDRO OVIEDO;" + 
				"ITAPUA,OBLIGADO;" + 
				"ITAPUA,MAYOR JULIO DIONISIO OTANO;" + 
				"ITAPUA,SAN COSME Y DAMIAN;" + 
				"ITAPUA,SAN PEDRO DEL PARANA;" + 
				"ITAPUA,SAN RAFAEL DEL PARANA;" + 
				"ITAPUA,TRINIDAD;" + 
				"ITAPUA,EDELIRA;" + 
				"ITAPUA,TOMAS ROMERO PEREIRA;" + 
				"ITAPUA,ALTO VERA;" + 
				"ITAPUA,LA PAZ;" + 
				"ITAPUA,YATYTAY;" + 
				"ITAPUA,SAN JUAN DEL PARANA;" + 
				"ITAPUA,PIRAPO;" + 
				"ITAPUA,ITAPUA POTY;" + 
				"MISIONES,SAN JUAN BAUTISTA DE LAS MISIONES;" + 
				"MISIONES,AYOLAS;" + 
				"MISIONES,SAN IGNACIO;" + 
				"MISIONES,SAN MIGUEL;" + 
				"MISIONES,SAN PATRICIO;" + 
				"MISIONES,SANTA MARIA;" + 
				"MISIONES,SANTA ROSA;" + 
				"MISIONES,SANTIAGO;" + 
				"MISIONES,VILLA FLORIDA;" + 
				"MISIONES,YABEBYRY;" + 
				"PARAGUARI,PARAGUARI;" + 
				"PARAGUARI,ACAHAY;" + 
				"PARAGUARI,CAAPUCU;" + 
				"PARAGUARI,CABALLERO;" + 
				"PARAGUARI,CARAPEGUA;" + 
				"PARAGUARI,ESCOBAR;" + 
				"PARAGUARI,LA COLMENA;" + 
				"PARAGUARI,MBUYAPEY;" + 
				"PARAGUARI,PIRAYU;" + 
				"PARAGUARI,QUIINDY;" + 
				"PARAGUARI,QUYQUYHO;" + 
				"PARAGUARI,ROQUE GONZALEZ DE SANTACRUZ;" + 
				"PARAGUARI,SAPUCAI;" + 
				"PARAGUARI,TEBICUARY-MI;" + 
				"PARAGUARI,YAGUARON;" + 
				"PARAGUARI,YBYCUI;" + 
				"PARAGUARI,YBYTYMI;" + 
				"ALTO PARANA,CIUDAD DEL ESTE;" + 
				"ALTO PARANA,PRESIDENTE FRANCO;" + 
				"ALTO PARANA,DOMINGO MARTINEZ DE IRALA;" + 
				"ALTO PARANA,DR. JUAN LEON MALLORQUIN;" + 
				"ALTO PARANA,HERNANDARIAS;" + 
				"ALTO PARANA,ITAKYRY;" + 
				"ALTO PARANA,JUAN E. O'LEARY;" + 
				"ALTO PARANA,NACUNDAY;" + 
				"ALTO PARANA,YGUAZU;" + 
				"ALTO PARANA,LOS CEDRALES;" + 
				"ALTO PARANA,MINGA GUAZU;" + 
				"ALTO PARANA,SAN CRISTOBAL;" + 
				"ALTO PARANA,SANTA RITA;" + 
				"ALTO PARANA,NARANJAL;" + 
				"ALTO PARANA,SANTA ROSA DEL MONDAY;" + 
				"ALTO PARANA,MINGA PORA;" + 
				"ALTO PARANA,MBARACAYU;" + 
				"ALTO PARANA,SAN ALBERTO;" + 
				"ALTO PARANA,IRUNA;" + 
				"ALTO PARANA,SANTA FE DEL PARANA;" + 
				"ALTO PARANA,TAVAPY;" + 
				"ALTO PARANA,DR. RAUL PENA;" + 
				"CENTRAL,AREGUA;" + 
				"CENTRAL,CAPIATA;" + 
				"CENTRAL,FERNANDO DE LA MORA;" + 
				"CENTRAL,GUARAMBARE;" + 
				"CENTRAL,ITA;" + 
				"CENTRAL,ITAUGUA;" + 
				"CENTRAL,LAMBARE;" + 
				"CENTRAL,LIMPIO;" + 
				"CENTRAL,LUQUE;" + 
				"CENTRAL,MARIANO ROQUE ALONSO;" + 
				"CENTRAL,NUEVA ITALIA;" + 
				"CENTRAL,NEMBY;" + 
				"CENTRAL,SAN ANTONIO;" + 
				"CENTRAL,SAN LORENZO;" + 
				"CENTRAL,VILLA ELISA;" + 
				"CENTRAL,VILLETA;" + 
				"CENTRAL,YPACARAI;" + 
				"CENTRAL,YPANE;" + 
				"CENTRAL,J. AUGUSTO SALDIVAR;" + 
				"NEEMBUCU,PILAR;" + 
				"NEEMBUCU,ALBERDI;" + 
				"NEEMBUCU,CERRITO;" + 
				"NEEMBUCU,DESMOCHADOS;" + 
				"NEEMBUCU,GRAL. JOSE EDUVIGIS DIAZ;" + 
				"NEEMBUCU,GUAZU-CUA;" + 
				"NEEMBUCU,HUMAITA;" + 
				"NEEMBUCU,ISLA UMBU;" + 
				"NEEMBUCU,LAURELES;" + 
				"NEEMBUCU,MAYOR JOSE DEJESUS MARTINEZ;" + 
				"NEEMBUCU,PASO DE PATRIA;" + 
				"NEEMBUCU,SAN JUAN BAUTISTA DE NEEMBUCU;" + 
				"NEEMBUCU,TACUARAS;" + 
				"NEEMBUCU,VILLA FRANCA;" + 
				"NEEMBUCU,VILLA OLIVA;" + 
				"NEEMBUCU,VILLALBIN;" + 
				"AMAMBAY,PEDRO JUAN CABALLERO;" + 
				"AMAMBAY,BELLA VISTA;" + 
				"AMAMBAY,CAPITAN BADO;" + 
				"AMAMBAY,ZANJA PYTÃ;" + 
				"AMAMBAY,KARAPAI;" + 
				"CANINDEYU,SALTO DEL GUAIRA;" + 
				"CANINDEYU,CORPUS CHRISTI;" + 
				"CANINDEYU,VILLA CURUGUATY;" + 
				"CANINDEYU,VILLA YGATIMI;" + 
				"CANINDEYU,ITANARA;" + 
				"CANINDEYU,YPEJHU;" + 
				"CANINDEYU,FRANCISCO CABALLERO ALVAREZ;" + 
				"CANINDEYU,KATUETE;" + 
				"CANINDEYU,LA PALOMA DEL ESPIRITU SANTO;" + 
				"CANINDEYU,NUEVA ESPERANZA;" + 
				"CANINDEYU,YASY CANY;" + 
				"CANINDEYU,YBYRAROBANA;" + 
				"CANINDEYU,YBY PYTA;" + 
				"PRESIDENTE HAYES,BENJAMIN ACEVAL;" + 
				"PRESIDENTE HAYES,PUERTO PINASCO;" + 
				"PRESIDENTE HAYES,VILLA HAYES;" + 
				"PRESIDENTE HAYES,NANAWA;" + 
				"PRESIDENTE HAYES,JOSE FALCON;" + 
				"PRESIDENTE HAYES,TTE. 1° MANUEL IRALA FERNANDEZ;" + 
				"PRESIDENTE HAYES,TENIENTE ESTEBAN MARTINEZ;" + 
				"PRESIDENTE HAYES,GENERAL JOSE MARIA BRUGUEZ;" + 
				"BOQUERON,MARISCAL JOSE FELIX ESTIGARRIBIA;" + 
				"BOQUERON,FILADELFIA;" + 
				"BOQUERON,LOMA PLATA;" + 
				"ALTO PARAGUAY,FUERTE OLIMPO;" + 
				"ALTO PARAGUAY,PUERTO CASADO;" + 
				"ALTO PARAGUAY,BAHIA NEGRA;" + 
				"ALTO PARAGUAY,CARMELO PERALTA";

		String [] depciu= datos.split(";");
		
		String ultimoDep = "";
		Departamento dep = null;
	
		for (int i = 0 ; i< depciu.length; i++) {
			
			System.out.println(depciu[i]);
			
			String[] aux = depciu[i].split(",");
			
			
			if (ultimoDep.compareTo(aux[0]) != 0) {

				Departamento auxDep = new Departamento();
				auxDep.setDepartamento(aux[0]);
				auxDep.setPais(pais);
				dep = reg.saveObject(auxDep, "System");
				
				ultimoDep = aux[0];
				
			}
			
			Ciudad ciu = new Ciudad();
			ciu.setDepartamento(dep);
			ciu.setCiudad(aux[1]);
			reg.saveObject(ciu,"System");
			
			
			
		}
		
	}

}
